# Generated by Django 6.1 on 2026-09-29 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robo',
            options={'permissions': [('executar_robo', 'Pode iniciar e parar robôs')]},
        ),
    ]
