# Generated by Django 6.1 on 2026-09-29 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retencao_dias', models.PositiveIntegerField(default=90, help_text='Por quantos dias guardar execuções e logs.', validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(3650)])),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuração do sistema',
                'permissions': [('gerenciar_usuarios', 'Pode gerenciar usuários e acesso'), ('ver_status_sistema', 'Pode ver o status do sistema'), ('gerenciar_retencao', 'Pode alterar a retenção do histórico'), ('gerenciar_limites', 'Pode alterar os limites padrão de execução')],
                'default_permissions': (),
            },
        ),
    ]
