# Generated by Django 6.1 on 2026-09-02 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('rodando', 'Rodando'), ('sucesso', 'Sucesso'), ('falha', 'Falha')], default='pendente', max_length=20)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('disparado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_disparadas', to=settings.AUTH_USER_MODEL)),
                ('robo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='robots.robo')),
            ],
        ),
    ]
