# Generated by Django 6.1 on 2026-09-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucao',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('agendamento', 'Agendamento')], default='manual', max_length=20),
        ),
    ]
