# Generated by Django 6.1 on 2026-09-29 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('segunda', models.BooleanField(default=True)),
                ('terca', models.BooleanField(default=True)),
                ('quarta', models.BooleanField(default=True)),
                ('quinta', models.BooleanField(default=True)),
                ('sexta', models.BooleanField(default=True)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_disparo', models.DateTimeField(blank=True, editable=False, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('robo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='robots.robo')),
            ],
            options={
                'ordering': ['horario'],
                'constraints': [models.UniqueConstraint(fields=('robo', 'horario'), name='agendamento_unico_por_horario')],
            },
        ),
    ]
